name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
